### ISSUE TITLE
Handling unordered equality for primitive arrays

### ISSUE THREAD

**Issue by SaumyaK-Temerity** [planttheidea/fast-equals#110]
Is it possible to add logic in order to handle primitive arrays such that the order is irrelevant? 
Because from my point of view, I would think that:  ```['4', '3']``` is equal to ```['3', '4']```, but it's not. 

So for equality, shouldn't these two be considered the same. Especially for things like "deep" equality?

I'm not too sure how deep the rabbit hole goes for trying to handle this for generic arrays, I imagine there's a lot more underlying complexity than what I understand...but just for arrays with only primitive elements...how difficult would this be to implement?

Or if it's possible to pass in an "unordered=true" type of optional argument that ignores the order for arrays?

**Comment by planttheidea** [comment]
I would say this is not in scope of the library to include by default, since this definition of equality differs from common expectations and other community examples, however absolutely possible with the current library.

I recommended looking at [`createCustomEqual`](https://github.com/planttheidea/fast-equals#createcustomequal), which can allow this flexibility. It may be as simple as sitting the inputs prior to checking.

**Comment by planttheidea** [comment]
Closng due to inactivity.
