### ISSUE TITLE
Undefined and missing are not equal

### ISSUE THREAD

**Issue by meelispr** [planttheidea/fast-equals#31]
`deepEqual({ foo: undefined }, {})` currently equals false  but for example when running the entities through serialisation `deepEqual(JSON.parse(JSON.stringify({ foo: undefined })), {})` then this is true.

**Comment by planttheidea** [comment]
Well yes, because you have modified the key => value structure of the object. Doing `JSON.parse(JSON.stringify(...))` inherently drops all undefined values. It is [part of the JSON.stringify spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description) to drop `undefined` values (and functions, and symbols).

We consider the two objects to be unequal because the own keys are different. If you want to make the comparison looser (e.g., consider a key whose value is `undefined` to be equal to the key not being declared), then I recommend creating [creating a custom equality comparator](https://github.com/planttheidea/fast-equals#createcustomequal), or using a normalizing step prior to the comparison (such as the approach you provide).

**Comment by meelispr** [comment]
it's not possible to create a custom comparator because this is the failing check and it's outside of the custom comparator:
https://github.com/planttheidea/fast-equals/blob/master/src/utils.ts#L377
