### ISSUE TITLE
Submit to lodash

### ISSUE THREAD

**Issue by kmiyashiro** [planttheidea/fast-equals#5]
Just wondering if you considered submitting this to lodash to replace the `_.isEqual` if it is so much faster and meets the spec?

**Comment by planttheidea** [comment]
Haha well appreciate the vote of confidence, but it wouldn't have much luck. Lodash is fantastic because they handle a variety of edge cases, the most notable of which is circular objects, which this library does not handle by default for performance reasons. This library handles the 95% use case in a very performant way, but lodash needs to handle that full 100%, which disqualifies this implementation.
