### ISSUE TITLE
Value of type '(a: any, b: any) => any' has no properties in common with type 'Partial<CreateComparatorCreatorOptions<undefined>>'

### ISSUE THREAD

**Issue by muh-hizbe** [planttheidea/fast-equals#87]
i got some error like below image. Sorry i'm newby in typescript and still learn. How to solve this error?

![image](https://user-images.githubusercontent.com/37175249/186566036-e0cffc77-d007-473c-b2e6-8902efd83f1a.png)
![image](https://user-images.githubusercontent.com/37175249/186566550-6928fc9b-41f3-4648-ae9f-8cf248da8afd.png)

**Comment by planttheidea** [comment]
Understandable, since TypeScript can produce some pretty opaque errors. In this case, it is revealing an actual problem with the code! My guess is you recently updated the version of `fast-equals` to v4, which has a breaking change related to `createCustomEqual`.

Starting in v4, instead of the callback receiving the `deepEqual` parameter, the callback passed to `createCustomEqual` receives an object of default type-specific handlers, and expects a return of a similar partial shape. The `CreateCustomComparatorOptions` are detailed [in the documentation](https://github.com/planttheidea/fast-equals/blob/master/README.md#createcustomequal), but I'll try to provide more targeted help here.

If you wanted to do a straight upgrade from the previous path, then you can use the `createIsNestedEqual` option. Something along these lines should work:

```ts
const deepEqualCompareForMaps = createCustomEqual(
  () => ({
    createNestedIsEqual: (deepEqual) => (a, b) => {
      if (isLatLngLiteral(a) || a instanceof google.maps.LatLng || isLatLngLiteral(b) || b instanceof googl.maps.LatLng) {
        return new google.maps.LatLng(a).equals(new google.maps.LatLng(b));
      }

      return deepEqual(a, b);
    },
  })
);
```

This has a 1-to-1 parity with previous, where the `deepEqual` method is composed but has specific logic for `LatLng`.

However, part of the reason for the breaking change is to allow more granular handling of equality comparisons, and this is a good example. In the above code, it will only check _nested_ `LatLng` values, however you can be more semantic, more performant, and potentially cover more use-cases if you instead override the `areObjectsEqual` option:

```ts
const deepEqualCompareForMaps = createCustomEqual(
  ({ areObjectsEqual }) => ({
    areObjectsEqual: (a, b) => {
      if (isLatLngLiteral(a) || a instanceof google.maps.LatLng || isLatLngLiteral(b) || b instanceof googl.maps.LatLng) {
        return new google.maps.LatLng(a).equals(new google.maps.LatLng(b));
      }

      return areObjectsEqual(a, b);
    }
  });
);
```

This will perform the same logic, however there are two distinctions:
- It will only operate on objects (other comparisons will avoid the `LatLng` checks, which is less work for all other types)
- It will apply on top-level, as well as nested, comparisons (if you pass `LatLng` objects directly, it will work the same)

This is all freehand coding, so it may not work out of the box, but hopefully it should give you some ideas about how to update the use of `createCustomEqual` for your needs.

**Comment by muh-hizbe** [comment]
thanks @planttheidea
