### ISSUE TITLE
angular cli bundles umd version instead of esm

### ISSUE THREAD

**Issue by atsjo** [planttheidea/fast-equals#89]
Warning from Angular-cli:
Warning: ... depends on 'fast-equals'. CommonJS or AMD dependencies can cause optimization bailouts.   
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I don't have this problem with any other libs exporting multiple module formats, and the problem here is probably that webpack prioritizes the "browser" export instead of "module" in package.json when both are available.

This can be fixed in multiple ways I guess, the esbuild docs (https://esbuild.github.io/api/#main-fields) mentions the below format when mixing browser and module exports...

{
  "main": "./node-cjs.js",
  "module": "./node-esm.js",
  "browser": {
    "./node-cjs.js": "./browser-cjs.js",
    "./node-esm.js": "./browser-esm.js"
  }
}

But maybe using the exports field is a better solution...

**Comment by planttheidea** [comment]
I can certainly look into this. While the recommendation and documentation you point to is `esbuild`-specific (which does not apply to this library, as it uses `rollup` for builds), there is something that is similar available in later versions of npm ... the [`exports` field](https://medium.com/swlh/npm-new-package-json-exports-field-1a7d1f489ccf). This is supported in node starting with version 13.2, and TypeScript starting with version 4.5, so it should help peeps on latest build dependencies. I'll need to do some research, though, to determine precedence over the older `main` / `module` / `browser` setup, and how that looks to determine if it is a breaking change (dropping older infrastructure support always is).

For your immediate needs, though ... it sounds like you are using `webpack` for your builds? If so, [`webpack` offers the ability to alias dependencies](https://webpack.js.org/configuration/resolve/#resolvealias) which may help. There are also more broad [resolution order options as well](https://webpack.js.org/configuration/resolve/#resolvemainfields), and if you've explicitly set the `target` (example: `target: 'web'`) then the `browser` field is ignored (per that documentation). This would also explain why you are seeing the above message, because `browser` is actually a _UMD_ export; only `main` is using a CJS export.

Hope this helps, and in the meantime I'll look into the newer export delegation options.

**Comment by atsjo** [comment]
Angular-cli abstracts away webpack, and give no easy options for customizing the webpack config used internally. It still works with this warning though, it just signals that it might not be able to tree-shake the module properly. I ended up trying dequals, which worked fine.

**Comment by ranma42** [comment]
It looks like the `.d.ts` files in the package reference the sources (also shipped within the package).
This might cause build errors depending on the TS build target:

```
Error: node_modules/fast-equals/src/utils.ts:91:10 - error TS2550: Property 'hasOwn' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2022' or later.

91   Object.hasOwn ||
            ~~~~~~
```

Apart from this, upgrading to the current next (beta.1) did not require any change to the app.
Thank you! :)

**Comment by planttheidea** [comment]
Thanks @ranma42 ! I'll refactor to make the `index.d.ts` the primary and everything else consume it, which should resolve the issue above. Appreciate the feedback!

**Comment by ranma42** [comment]
Confirmed, `beta.2` makes the build go just fine even without any change to tsconfig. Thank you for the quick fix!

**Comment by atsjo** [comment]
tested with beta 6 and angular, and cli/build doesn't report any warnings now:-)

**Comment by planttheidea** [comment]
Great! If I get some time this weekend I'll take it out of beta, cuz I think it's ready. Thanks for the feedback!

**Comment by planttheidea** [comment]
`5.0.0` has been published with better support for different build environments. If you have any more issues, let me know!
