### ISSUE TITLE
Any plans of support Typed Arrays equality comparison?

### ISSUE THREAD

**Issue by Semigradsky** [planttheidea/fast-equals#97]
It currently supported by `fast-deep-equal`/`react-fast-compare`, `lodash`/`undersore`.

**Comment by planttheidea** [comment]
I can certainly add TypedArray support. I believe I already have it for `fast-copy`, so this would provide parity as well. The logic doesn't look too tricky, so I'll try to include it for `5.0.0-beta.4`.

**Comment by planttheidea** [comment]
Alright, `5.0.0-beta.4` is released, and includes support for TypedArrays. It aligns with the aforementioned libraries in standard mode (`deepEqual` / `shallowEqual`), however in strict mode (`strictDeepEqual` / `strictShallowEqual`) it also will compare the constructors to verify they are the same. I didn't have this prior, but it seemed reasonable given we are performing strict checks.

Feel free to check it out at let me know if it works for your needs. FWIW, in my local benchmark tests it was trading top spots with `react-fast-compare` (they were always within the margin of error of one another), and was about 1.7x faster than `fast-deep-equal`.

**Comment by planttheidea** [comment]
Hmm yeah I see checking constructor equality is pretty consistent across different libraries. Since I'm doing this as part of a major version update, I'll include this additional check for all modes, not just strict mode. Thanks for the call out.

I'm still tweaking the strict mode for TypedArrays, because I believe I'm duplicating work unnecessarily, so expect another beta or two before v5 is official.

**Comment by planttheidea** [comment]
Alright, `5.0.0-beta.6` has been published, and `constructor` equality is now a requirement. I've also fixed the duplicative work for TypedArrays, so this should hopefully be the last beta (assuming no further issues).

**Comment by planttheidea** [comment]
`5.0.0` has been published with TypedArray support. Let me know if you have any more issues!
